timer:
  second: 5  #配置最好不要大于linux time_wait 回收时间

influx:
  url: 
  user: admin
  password: 
  db: apimetrics
  precision: ms

modules:
  test_get:
    mothod: GET
    url:
      baidu: 
        - http://www.baidu.com
        - 2.2.2.2

      juejin:
        - http://www.juejin.cn
        - 1.1.1.1

  test_post:
    mothod: POST
    body: '{"jsonrpc": "2.0", "method": "cfx_epochNumber", "params": [], "id": 1}'
    url:
      infura_testnet-bj-test: 
        - http://test.confluxrpc.com
        - 123.57.249.249
 
      infura_mainnet-bj-main:
        - http://main.confluxrpc.com
        - 8.140.19.93