influx:
  url: 
  user: admin
  password: 
  db: apimetrics
  precision: ms

modules:
  baidu_get:
    mothod: GET
    url:
      - http://www.baidu.com
      - https://juejin.cn

  baidu_post:
    mothod: POST
    body: '{"jsonrpc": "2.0", "method": "cfx_epochNumber", "params": [], "id": 1}'
    url:
      - http://www.baidu.com
      - https://juejin.cn