timer:
  second: 30  #配置最好不要大于linux time_wait 回收时间

influx:
  url: 
  user: admin
  password: 
  db: apimetrics
  precision: ms

modules:
  test_get:
    mothod: GET
    url:
      baidu: http://www.baidu.com
      juejin: http://www.juejin.cn

  test_post:
    mothod: POST
    body: '{"jsonrpc": "2.0", "method": "cfx_epochNumber", "params": [], "id": 1}'
    url:
      infura_testnet-bj-test: 
      infura_mainnet-bj-main: