timer:
  second: 30  #配置最好不要小于linux time_wait 回收时间

influx:
  url: 
  user: admin
  password: 
  db: apimetrics
  precision: ns #(use n, u, ms, s, m or h)

modules:
  get:
    mothod: GET
    url:
      nft_get: https://nfttest.confluxnetwork.org
      scan_get: https://www.confluxscan.io
      devops_test-get: https://10minutemail.net

  publicrpc_post:
    mothod: POST
    body: '{"jsonrpc": "2.0", "method": "cfx_epochNumber", "params": [], "id": 1}'
    url:
      infura_testnet-bj-post-test: 
      infura_mainnet-bj-post-main: 