timed_task:
  second: 30

influx:
  url: 
  user: 
  password: 
  db: 
  precision: ms

modules:
  baidu_get:
    mothod: GET
    url:
      - http://www.baidu.com

  baidu_post_epochnumber:
    mothod: POST
    body: '{"jsonrpc": "2.0", "method": "", "params": [], "id": 1}'
    url:
      - http://www.baidu.com