timer:
  second: 180  #配置最好不要小于linux time_wait 回收时间

influx:
  url: 
  user: admin
  password: 
  db: 
  precision: ns #(use n, u, ms, s, m or h)

depends:
  getBlock:
    params: result.hash #过滤接口返回值
    default_value: "" #依赖key请求不到，设置默认key
    body: ''

modules:
  get:
    mothod: GET
    url:
      baidu: https://www.baidu.com

  test1:
    mothod: POST
    body: ''
    url:
      baidu: https://www.baidu.com

  test2:
    mothod: POST
    body:  ""
    depend: getBlock
    url:
      google: https://google.cn